"""update db

Revision ID: 6fbe0978a8d7
Revises: 8746f11a703d
Create Date: 2025-02-20 15:50:50.663895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fbe0978a8d7'
down_revision = '8746f11a703d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('convention_area_host')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('convention_area_host',
    sa.Column('convention_area_id', sa.INTEGER(), nullable=False),
    sa.Column('host_company_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['convention_area_id'], ['convention_areas.id'], name='fk_convention_area_host_convention_area_id_convention_areas'),
    sa.ForeignKeyConstraint(['host_company_id'], ['host_companies.id'], name='fk_convention_area_host_host_company_id_host_companies'),
    sa.PrimaryKeyConstraint('convention_area_id', 'host_company_id', name='pk_convention_area_host')
    )
    # ### end Alembic commands ###
