"""empty message

Revision ID: 8746f11a703d
Revises: 69d4ef9425fd
Create Date: 2025-02-14 01:05:58.858427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8746f11a703d'
down_revision = '69d4ef9425fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('convention_area_host',
    sa.Column('convention_area_id', sa.Integer(), nullable=False),
    sa.Column('host_company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['convention_area_id'], ['convention_areas.id'], name=op.f('fk_convention_area_host_convention_area_id_convention_areas')),
    sa.ForeignKeyConstraint(['host_company_id'], ['host_companies.id'], name=op.f('fk_convention_area_host_host_company_id_host_companies')),
    sa.PrimaryKeyConstraint('convention_area_id', 'host_company_id', name=op.f('pk_convention_area_host'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('convention_area_host')
    # ### end Alembic commands ###
